# Under the Hood of Encrypted Neural Networks

This tutorial is optional, and can be skipped without loss of continuity.

In this tutorial, we'll take a look at how CrypTen performs inference with an encrypted neural network on encrypted data. We'll see how the data remains encrypted through all the operations, and yet is able to obtain accurate results after the computation. 

In [1]:
import crypten
import torch

crypten.init() 
torch.set_num_threads(1)

# Ignore warnings
import warnings; 
warnings.filterwarnings("ignore")

# Keep track of all created temporary files so that we can clean up at the end
temp_files = []

## A Simple Linear Layer
We'll start by examining how a single Linear layer works in CrypTen. We'll instantiate a torch Linear layer, convert to CrypTen layer, encrypt it, and step through some toy data with it. As in earlier tutorials, we'll assume Alice has the rank 0 process and Bob has the rank 1 process. We'll also assume Alice has the layer and Bob has the data.

In [2]:
# Define ALICE and BOB src values
ALICE = 0
BOB = 1

In [3]:
import torch.nn as nn

# Instantiate single Linear layer
layer_linear = nn.Linear(4, 2)

# The weights and the bias are initialized to small random values
print("Plaintext Weights:\n\n", layer_linear._parameters['weight'])
print("\nPlaintext Bias:\n\n", layer_linear._parameters['bias'])

# Save the plaintext layer
layer_linear_file = "/tmp/tutorial5_layer_alice1.pth"
crypten.save(layer_linear, layer_linear_file)
temp_files.append(layer_linear_file) 

# Generate some toy data
features = 4
examples = 3
toy_data = torch.rand(examples, features)

# Save the plaintext toy data
toy_data_file = "/tmp/tutorial5_data_bob1.pth"
crypten.save(toy_data, toy_data_file)
temp_files.append(toy_data_file)

Plaintext Weights:

 Parameter containing:
tensor([[-0.4258, -0.4130, -0.4771, -0.4829],
        [-0.0176,  0.4334,  0.4345,  0.1994]], requires_grad=True)

Plaintext Bias:

 Parameter containing:
tensor([-0.3670, -0.3700], requires_grad=True)


In [4]:
import crypten.mpc as mpc
import crypten.communicator as comm

@mpc.run_multiprocess(world_size=2)
def forward_single_encrypted_layer():
    # Load and encrypt the layer
    layer = crypten.load_from_party(layer_linear_file, src=ALICE)
    layer_enc = crypten.nn.from_pytorch(layer, dummy_input=torch.empty((1,4)))
    layer_enc.encrypt(src=ALICE)
    
    # Note that layer parameters are encrypted:
    crypten.print("Weights:\n", layer_enc.weight.share)
    crypten.print("Bias:\n", layer_enc.bias.share, "\n")
    
    # Load and encrypt data
    data_enc = crypten.load_from_party(toy_data_file, src=BOB)
    
    # Apply the encrypted layer (linear transformation):
    result_enc = layer_enc.forward(data_enc)
    
    # Decrypt the result:
    result = result_enc.get_plain_text()
    
    # Examine the result
    crypten.print("Decrypted result:\n", result)
        
forward_single_encrypted_layer()

Weights:
 tensor([[ 4809765439338565026, -8528297308125766579, -9049258375232459840,
          2844226043919239965],
        [-3908530731123408934,  1774359065878558133,  2533144602464543266,
         -3356227231624953279]])
Bias:
 tensor([-7879285751097988616, -1952849712014642234]) 

Decrypted result:
 tensor([[-1.0097,  0.1116],
        [-1.5431,  0.2374],
        [-1.3470,  0.1359]])


[None, None]

We can see that the application of the encrypted linear layer on the encrypted data produces an encrypted result, which we can then decrypt to get the values in plaintext.

Let's look at a second linear transformation, to give a flavor of how accuracy is preserved even when the data and the layer are encrypted. We'll look at a uniform scaling transformation, in which all tensor elements are multiplied by the same scalar factor. Again, we'll assume Alice has the layer and the rank 0 process, and Bob has the data and the rank 1 process.

In [5]:
# Initialize a linear layer with random weights
layer_scale = nn.Linear(3, 3)

# Construct a uniform scaling matrix: we'll scale by factor 5
factor = 5
layer_scale._parameters['weight'] = torch.eye(3)*factor
layer_scale._parameters['bias'] = torch.zeros_like(layer_scale._parameters['bias'])

# Save the plaintext layer
layer_scale_file = "/tmp/tutorial5_layer_alice2.pth"
crypten.save(layer_scale, layer_scale_file)
temp_files.append(layer_scale_file)

# Construct some toy data
features = 3
examples = 2
toy_data = torch.ones(examples, features)

# Save the plaintext toy data
toy_data_file = "/tmp/tutorial5_data_bob2.pth"
crypten.save(toy_data, toy_data_file)
temp_files.append(toy_data_file)

In [6]:
@mpc.run_multiprocess(world_size=2)
def forward_scaling_layer():
    rank = comm.get().get_rank()
    
    # Load and encrypt the layer
    layer = crypten.load_from_party(layer_scale_file, src=ALICE)
    layer_enc = crypten.nn.from_pytorch(layer, dummy_input=torch.empty((1,3)))
    layer_enc.encrypt(src=ALICE)
    
    # Load and encrypt data
    data_enc = crypten.load_from_party(toy_data_file, src=BOB)   
    
    # Note that layer parameters are (still) encrypted:
    crypten.print("Weights:\n", layer_enc.weight)
    crypten.print("Bias:\n\n", layer_enc.bias)

    # Apply the encrypted scaling transformation
    result_enc = layer_enc.forward(data_enc)

    # Decrypt the result:
    result = result_enc.get_plain_text()
    crypten.print("Plaintext result:\n", (result))
        
z = forward_scaling_layer()

Weights:
 tensor([[ 1048173932012528739, -8485385189168951104, -4402857909290748548],
        [ 4553819400594206674, -7570443770611756974, -5679305187004366181],
        [-1176794114084926816,   871515787882802395,  6055415794932662708]])
Bias:

 tensor([-2824390750419204213,  3169342280882583467,  2952982236928138320])
Plaintext result:
 tensor([[5., 5., 5.],
        [5., 5., 5.]])


The resulting plaintext tensor is correctly scaled, even though we applied the encrypted transformation on the encrypted input! 

## Multi-layer Neural Networks
Let's now look at how the encrypted input moves through an encrypted multi-layer neural network. 

For ease of explanation, we'll first step through a network with only two linear layers and ReLU activations. Again, we'll assume Alice has a network and Bob has some data, and they wish to run encrypted inference. 

To simulate this, we'll once again generate some toy data and train Alice's network on it. Then we'll encrypt Alice's network, Bob's data, and step through every layer in the network with the encrypted data. Through this, we'll see how the computations get applied although the network and the data are encrypted.

### Setup
As in Tutorial 3, we will first generate 1000 ground truth samples using 50 features and a randomly generated hyperplane to separate positive and negative examples. We will then modify the labels so that they are all non-negative. Finally, we will split the data so that the first 900 samples belong to Alice and the last 100 samples belong to Bob.

In [7]:
# Setup
features = 50
examples = 1000

# Set random seed for reproducibility
torch.manual_seed(1)

# Generate toy data and separating hyperplane
data = torch.randn(examples, features)
w_true = torch.randn(1, features)
b_true = torch.randn(1)
labels = w_true.matmul(data.t()).add(b_true).sign()

# Change labels to non-negative values
labels_nn = torch.where(labels==-1, torch.zeros(labels.size()), labels)
labels_nn = labels_nn.squeeze().long()

# Split data into Alice's and Bob's portions:
data_alice, labels_alice = data[:900], labels_nn[:900]
data_bob, labels_bob = data[900:], labels_nn[900:]

In [8]:
# Define Alice's network
import torch.nn as nn
import torch.nn.functional as F

class AliceNet(nn.Module):
    def __init__(self):
        super(AliceNet, self).__init__()
        self.fc1 = nn.Linear(50, 20)
        self.fc2 = nn.Linear(20, 2)
        
    def forward(self, x):
        out = self.fc1(x)
        out = F.relu(out)
        out = self.fc2(out)
        return out

In [9]:
# Train and save Alice's network
model = AliceNet()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

for i in range(500):  
    #forward pass: compute prediction
    output = model(data_alice)
    
    #compute and print loss
    loss = criterion(output, labels_alice)
    if i % 100 == 99:
        print("Epoch", i, "Loss:", loss.item())
    
    #zero gradients for learnable parameters
    optimizer.zero_grad()
    
    #backward pass: compute gradient with respect to model parameters
    loss.backward()
    
    #update model parameters
    optimizer.step()

sample_trained_model_file = '/tmp/tutorial5_alice_model.pth'
torch.save(model, sample_trained_model_file)
temp_files.append(sample_trained_model_file)

Epoch 99 Loss: 0.24704290926456451
Epoch 199 Loss: 0.08965438604354858
Epoch 299 Loss: 0.05166155472397804
Epoch 399 Loss: 0.03510778397321701
Epoch 499 Loss: 0.026072457432746887


### Stepping through a Multi-layer Network

Let's now look at what happens when we load the network Alice's has trained and encrypt it. First, we'll look at how the network structure changes when we convert it from a PyTorch network to CrypTen network.

In [10]:
# Load the trained network to Alice
model_plaintext = crypten.load(sample_trained_model_file, model_class=AliceNet, src=ALICE)

# Convert the trained network to CrypTen network 
private_model = crypten.nn.from_pytorch(model_plaintext, dummy_input=torch.empty((1, 50)))
# Encrypt the network
private_model.encrypt(src=ALICE)

# Examine the structure of the encrypted CrypTen network
for name, curr_module in private_model._modules.items():
    print("Name:", name, "\tModule:", curr_module)

Name: 5 	Module: Linear encrypted module
Name: 6 	Module: ReLU encrypted module
Name: output 	Module: Linear encrypted module


We see that the encrypted network has 3 modules, named '5', '6' and 'output', denoting the first Linear layer, the ReLU activation, and the second Linear layer respectively. These modules are encrypted just as the layers in the previous section were. 

Now let's encrypt Bob's data, and step it through each encrypted module. For readability, we will use only 3 examples from Bob's data to illustrate the inference. Note how Bob's data remains encrypted after each individual layer's computation!

In [11]:
# Pre-processing: Select only the first three examples in Bob's data for readability
data = data_bob[:3]
sample_data_bob_file = '/tmp/tutorial5_data_bob3.pth'
torch.save(data, sample_data_bob_file)
temp_files.append(sample_data_bob_file)

In [13]:
@mpc.run_multiprocess(world_size=2)
def step_through_two_layers():    
    rank = comm.get().get_rank()

    # Load and encrypt the network
    model = crypten.load_from_party(sample_trained_model_file, model_class=AliceNet, src=ALICE)
    private_model = crypten.nn.from_pytorch(model, dummy_input=torch.empty((1, 50)))
    private_model.encrypt(src=ALICE)

    # Load and encrypt the data
    data_enc = crypten.load(sample_data_bob_file, src=BOB)

    # Forward through the first layer
    out_enc = private_model._modules['5'].forward(data_enc)
    encrypted = crypten.is_encrypted_tensor(out_enc)
    crypten.print(f"Rank: {rank}\n\tFirst Linear Layer: Output Encrypted: {encrypted}", in_order=True)
    crypten.print(f"Rank: {rank}\n\tShares after First Linear Layer:{out_enc.share}", in_order=True)

    # Apply ReLU activation
    out_enc = private_model._modules['6'].forward(out_enc)
    encrypted = crypten.is_encrypted_tensor(out_enc)
    crypten.print(f"Rank: {rank}\n\tReLU:\n Output Encrypted: {encrypted}", in_order=True)
    crypten.print(f"Rank: {rank}\n\tShares after ReLU: {out_enc.share}\n", in_order=True)

    # Forward through the second Linear layer
    out_enc = private_model._modules['output'].forward(out_enc)
    encrypted = crypten.is_encrypted_tensor(out_enc)
    crypten.print(f"Rank: {rank} Second Linear layer:\n Output Encrypted: {encrypted}\n", in_order=True) 
    crypten.print(f"Rank: {rank} Shares after Second Linear layer:{out_enc.share}\n", in_order=True)

    # Decrypt the output
    out_dec = out_enc.get_plain_text()
    
    # Since both parties have same decrypted results, only print the rank 0 output
    crypten.print("Decrypted output:\n Output Encrypted:", crypten.is_encrypted_tensor(out_dec))
    crypten.print("Tensors:\n", out_dec)
    
z = step_through_two_layers()

Rank: 0
	First Linear Layer: Output Encrypted: True
Rank: 1
	First Linear Layer: Output Encrypted: True
Rank: 0
	Shares after First Linear Layer:tensor([[ 1294104436359772009,   175627571159595069,  6642614375759992943,
          6081499958679808446,  7458846727696033441,  3147092037857368600,
         -3046033583744813218,  3656714442306812623, -1444801573761934624,
         -7296071273089953465,  8612281116080325317,  3767966956893906701,
          1168460730848498997,  6391421666103853539,  2248247350390000515,
          3213300948547734905, -1008946278573850451,  3023665117027050103,
          6452227059867486924,  5122606758130927186],
        [ 1294098018270385457,   175572314767882774,  6642679547617989340,
          6081490500342724210,  7458890389841627996,  3146958713752628383,
         -3046031468676736309,  3656827531990650240, -1444926189414126081,
         -7295908481581646714,  8612296818825007185,  3767896044585741179,
          1168492541025886293,  6391421981103357070

Again, we emphasize that the output of each layer is an encrypted tensor. Only after the final call to `get_plain_text` do we get the plaintext tensor.

### From PyTorch to CrypTen: Structural Changes in Network Architecture 

We have used a simple two-layer network in the above example, but the same ideas apply to more complex networks and operations. However, in more complex networks, there may not always be a one-to-one mapping between the PyTorch layers and the CrypTen layers. This is because we use PyTorch's onnx implementation to convert PyTorch models to CrypTen models. 
As an example, we'll take a typical network used to classify digits in MNIST data, and look at what happens to its structure we convert it to a CrypTen module. (As we only wish to illustrate the structural changes in layers, we will not train this network on data; we will just use it with its randomly initialized weights). 

In [13]:
# Define Alice's network
class AliceNet2(nn.Module):
    def __init__(self):
        super(AliceNet2, self).__init__()
        self.conv1 = nn.Conv2d(1, 16, kernel_size=5, padding=0)
        self.conv2 = nn.Conv2d(16, 16, kernel_size=5, padding=0)
        self.fc1 = nn.Linear(16 * 4 * 4, 100)
        self.fc2 = nn.Linear(100, 10)
        self.batchnorm1 = nn.BatchNorm2d(16)
        self.batchnorm2 = nn.BatchNorm2d(16)
        self.batchnorm3 = nn.BatchNorm1d(100)
 
    def forward(self, x):
        out = self.conv1(x)
        out = self.batchnorm1(out)
        out = F.relu(out)
        out = F.avg_pool2d(out, 2)
        out = self.conv2(out)
        out = self.batchnorm2(out)
        out = F.relu(out)
        out = F.avg_pool2d(out, 2)
        out = out.view(out.size(0), -1)
        out = self.fc1(out)
        out = self.batchnorm3(out)
        out = F.relu(out)
        out = self.fc2(out)
        return out
    
model = AliceNet2()

# Let's encrypt the complex network. 
# Create dummy input of the correct input shape for the model
dummy_input = torch.empty((1, 1, 28, 28))

# Encrypt the network
private_model = crypten.nn.from_pytorch(model, dummy_input)
private_model.encrypt(src=ALICE)

# Examine the structure of the encrypted network
for name, curr_module in private_model._modules.items():
    print("Name:", name, "\tModule:", curr_module)

Name: 46 	Module: Conv2d encrypted module
Name: 26 	Module: ReLU encrypted module
Name: 27 	Module: _ConstantPad encrypted module
Name: 28 	Module: AvgPool2d encrypted module
Name: 49 	Module: Conv2d encrypted module
Name: 31 	Module: ReLU encrypted module
Name: 32 	Module: _ConstantPad encrypted module
Name: 33 	Module: AvgPool2d encrypted module
Name: 34 	Module: Shape encrypted module
Name: 36 	Module: Gather encrypted module
Name: 37 	Module: Constant encrypted module
Name: 38 	Module: Unsqueeze encrypted module
Name: 39 	Module: Unsqueeze encrypted module
Name: 40 	Module: Concat encrypted module
Name: 41 	Module: Reshape encrypted module
Name: 42 	Module: Linear encrypted module
Name: 43 	Module: _BatchNorm encrypted module
Name: 44 	Module: ReLU encrypted module
Name: output 	Module: Linear encrypted module


Notice how the CrypTen network has split some the layers in the PyTorch module into several CrypTen modules. Each PyTorch operation may correspond to one or more operations in CrypTen. However, during the conversion, these are sometimes split due to limitations intorduced by onnx.

Before exiting this tutorial, please clean up the files generated using the following code.

In [14]:
import os
for fn in temp_files:
    if os.path.exists(fn): os.remove(fn)